### ISSUE TITLE
Unable to establish two QUIC connection on the same receiver

### ISSUE THREAD

**Issue by muhammadeid172** [signetlabdei/quic-ns-3#46]
Hi,

I'm trying to establish two QUIC connections, both from node0 to node1, but I'm countering an error.
I tried to investigate why is that happening. After adding the following prints in the QUIC module (```quic-socket-base.cc``` file):
![quic-socket-base.cc edit](https://github.com/signetlabdei/quic-ns-3/assets/94244691/c141cf1c-5e21-4305-ab0e-76469459e5e7)

I got the following result:
![Two different sockets use the same QuicL4Protocol object](https://github.com/signetlabdei/quic-ns-3/assets/94244691/03196e79-e15e-44e9-9eb0-963c54b9a4e2)

From the results I got, I can see that two different ```QuicSocketBase``` objects are using the same ```QuicL4Protocol``` object.
Is this by design? I think this is something worth reviewing, hopefully it would resolve the error.

In case it is needed, this is the full simulation I'm trying to run: https://github.com/muhammadeid172/QUIC-vs-TCP-A-Performance-Evaluation-over-LTE-with-NS-3/blob/main/FailedAttempts/TwoQuicConnectionsSameReceiver.cc

Thanks! :)

**Comment by fedech** [comment]
This is not something we explicitly thought of, because of the streams feature (which would allow multiple logically separate flows of data to operate over a single QUIC connection, with the benefits of a single congestion control, not having to set up multiple connections, etc.). At the moment this is unsupported, but we will consider it in the next update of the module. The quic-l4-protocol.cc code is already designed to be general, it should be relatively easy to adapt
